### ISSUE TITLE
CSS file is empty

### ISSUE THREAD

**Issue by gabrielsroka** [wilsmex/edu#1]
Hi, I really enjoyed your YouTube video:
https://www.youtube.com/watch?v=gH3sBOj6CGA

I'm trying out the code here, but the CSS file is 0 bytes -- empty.

Would you please upload it again?

Thanks!

**Comment by aakash981** [comment]
I'm trying out the code here, but the CSS file is 0 bytes -- empty.

Would you please upload it again?

Thanks!

**Comment by wilsmex** [comment]
Added finished css file
